; Ejemplo de BDC.INI
[base_de_datos]
; Ruta completa al fichero de base de datos SQLite.
; Si no se especifica, se usa bdc.db junto al ejecutable.
;ruta=C:\Users\usuario\Documents\bdc.db
ruta=/home/usuario/Documentos/bdc/bdc.db
